/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soccer.talk;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static soccer.talk.LoginFrame.v;

/**
 *
 * @author PB
 */
public class ContaFrame extends javax.swing.JFrame {

    private static String senha = "";
    private static String celular = "";
    private static String nome = "";
    private static String time = "";
    private static String sexo = "";

    public static String getSenha() {
        return senha;
    }

    public static String getCelular() {
        return celular;
    }

    public static String getNome() {
        return nome;
    }

    public static String getTime() {
        return time;
    }

    public static String getSexo() {
        return sexo;
    }

    public ContaFrame() {
        initComponents();
        try {
            LoginFrame.clienteContaSerializada = LoginFrame.lerContasSer();

            LoginFrame.v = false;
            
            celular = LoginFrame.getLoginCelular();
            senha = LoginFrame.getLoginSenha();
            nome = LoginFrame.getLoginNome();
            time = LoginFrame.getLoginTime();
            sexo = LoginFrame.getLoginSexo();
            lblNome.setText(nome);
            
            
            if(time.equals("SFC")){
                lblTime.setText("Santos Futebol Clube");
                lblTime.setForeground(new java.awt.Color(102, 102, 102));
                lblNome.setForeground(new java.awt.Color(102, 102, 102));
                lblNome1.setForeground(new java.awt.Color(102, 102, 102));
                jPanel1.setBackground(new java.awt.Color(204, 204, 204));
                imgTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SFCmini.jpg")));
            }else if(time.equals("SPFC")){
                lblTime.setText("São Paulo Futebol Clube");
                lblTime.setForeground(new java.awt.Color(255, 255, 255));
                lblNome.setForeground(new java.awt.Color(255, 255, 255));
                jPanel1.setBackground(new java.awt.Color(220, 0, 0));
                imgTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SPFCmini.jpg")));
            }else if(time.equals("SCCP")){
                lblTime.setText("Sport Clube Corinthians Paulista");
                lblTime.setForeground(new java.awt.Color(255, 255, 255));
                lblNome.setForeground(new java.awt.Color(255, 255, 255));
                lblNome1.setForeground(new java.awt.Color(255, 255, 255));
                lblSenhaAtual.setForeground(new java.awt.Color(255, 255, 255));
                lblSenhaNova.setForeground(new java.awt.Color(255, 255, 255));
                lblSexo.setForeground(new java.awt.Color(255, 255, 255));
                jPanel1.setBackground(new java.awt.Color(30, 30, 30));
                imgTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SCCPmini.jpg")));
            }else if(time.equals("SEP")){
                lblTime.setText("Sociedade Esportiva Palmeiras");
                lblTime.setForeground(new java.awt.Color(255, 255, 255));
                lblNome.setForeground(new java.awt.Color(255, 255, 255));
                jPanel1.setBackground(new java.awt.Color(0, 151, 0));
                imgTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPmini.jpg")));
            }
            
            if(sexo.equals("Masculino")){
                lblSexo.setText("Masculino");
            } else if(sexo.equals("Feminino")){
                lblSexo.setText("Feminino");
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(ContaFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ContaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtSenhaAtual = new javax.swing.JPasswordField();
        btnSair = new javax.swing.JButton();
        lblSenhaNova = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblSenhaAtual = new javax.swing.JLabel();
        txtSenhaNova = new javax.swing.JPasswordField();
        btnConectar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        pnTime = new javax.swing.JPanel();
        imgTime = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        btnConectarTime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 480));
        setPreferredSize(new java.awt.Dimension(320, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(320, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 255, 255)));

        lblNome.setBackground(new java.awt.Color(255, 255, 255));
        lblNome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblNome.setText("NomeDoUsuário");

        txtSenhaAtual.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 0)));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblSenhaNova.setBackground(new java.awt.Color(255, 255, 255));
        lblSenhaNova.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSenhaNova.setText("Nova Senha: ");

        lblNome1.setBackground(new java.awt.Color(255, 255, 255));
        lblNome1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblNome1.setText("Nome: ");

        lblSenhaAtual.setBackground(new java.awt.Color(255, 255, 255));
        lblSenhaAtual.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblSenhaAtual.setText("Senha Atual: ");

        txtSenhaNova.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        btnConectar.setBackground(new java.awt.Color(255, 0, 0));
        btnConectar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnConectar.setForeground(new java.awt.Color(255, 255, 255));
        btnConectar.setText("Chat Padrão");
        btnConectar.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 0)));
        btnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 255, 0));
        btnAlterar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 0)));
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        pnTime.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 0)));
        pnTime.setMaximumSize(new java.awt.Dimension(110, 110));
        pnTime.setMinimumSize(new java.awt.Dimension(110, 110));
        pnTime.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout pnTimeLayout = new javax.swing.GroupLayout(pnTime);
        pnTime.setLayout(pnTimeLayout);
        pnTimeLayout.setHorizontalGroup(
            pnTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgTime, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnTimeLayout.setVerticalGroup(
            pnTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgTime, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTime.setText("TimeDoUsuário");

        lblSexo.setBackground(new java.awt.Color(255, 255, 255));
        lblSexo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSexo.setText("Sexo: ");

        btnConectarTime.setBackground(new java.awt.Color(255, 255, 0));
        btnConectarTime.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnConectarTime.setText("Chat Time");
        btnConectarTime.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 0)));
        btnConectarTime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConectarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(btnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConectarTime, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNome))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSexo))
                                    .addComponent(lblTime)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSenhaAtual)
                                    .addComponent(lblSenhaNova))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNome1))
                .addGap(1, 1, 1)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addComponent(pnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAtual)
                    .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaNova)
                    .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectar)
                    .addComponent(btnConectarTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnSair))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try (Connection con = DriverManager.getConnection(LoginFrame.url, "scott", "tiger")){
            LoginFrame.clienteConta = LoginFrame.lerContas(con);

            for (ClienteConta conta : LoginFrame.clienteConta) {
                if (conta.getCelular().equals(celular)) {
                    if (conta.getSenha().equals(txtSenhaAtual.getText())) {
                        conta.setSenha(txtSenhaNova.getText());
                        LoginFrame.alterarSenha(con, LoginFrame.clienteConta, celular, txtSenhaNova.getText());
                        JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!");

                        txtSenhaAtual.setText("");
                        txtSenhaNova.setText("");
                        
                        
                        
                        break;
                    } else {
                        JOptionPane.showMessageDialog(this, "Senha atual está incorreta!");
                        txtSenhaAtual.setText("");
                        txtSenhaNova.setText("");
                        break;
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ContaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        new ChatPadraoFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConectarTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarTimeActionPerformed
        if(time.equals("SFC")){
            new ChatSFCFrame().setVisible(true);
            dispose();
        } else if(time.equals("SPFC")){
            new ChatSPFCFrame().setVisible(true);
            dispose();
        } else if(time.equals("SEP")){
            new ChatSEPFrame().setVisible(true);
            dispose();
        } else if(time.equals("SCCP")){
            new ChatSCCPFrame().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnConectarTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnConectarTime;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel imgTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblSenhaAtual;
    private javax.swing.JLabel lblSenhaNova;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnTime;
    private javax.swing.JPasswordField txtSenhaAtual;
    private javax.swing.JPasswordField txtSenhaNova;
    // End of variables declaration//GEN-END:variables
}
